name: Node.js vite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: dist/
